// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.


import * as T from "../types/index"


export interface IEventWindowMany {

    /**
**/
    emitMainEvent(payload: T.MainPayload): Promise<void>;

    /**
**/
    emitSubEvent(payload: T.SubPayload): Promise<void>;

    /**
**/
    emitAnotherMainEvent(): Promise<void>;

}