
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : nesting_type_test.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../interface/';

// tauri command interface class 
// target file : nesting_type_test.rs
class NestingTypeTest implements T.INestingTypeTest {

    //#region #tauri command
    
    /**
* * @brief Processes a given message.* * @param msg The message to process.* * @returns A string indicating the processed message.*/
    async process_message(msg: T.Data): Promise<string> {
        return await invoke('process_message', { msg: msg });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.INestingTypeTest  {
        return new NestingTypeTest();
    }
    //#endregion

}

// factory function
export function createNestingTypeTest(): T.INestingTypeTest {
    return NestingTypeTest.create();
}
