// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.



export interface IState {

    /**
**/
    testState(): Promise<void>;

    /**
**/
    testState2(name: string): Promise<void>;

    /**
**/
    testState3(name: string): Promise<void>;

}