
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : event_global.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../interface/';

// tauri command interface class 
// target file : event_global.rs
class EventGlobal implements T.IEventGlobal {

    //#region #tauri command
    
    /**
**/
    async appHandleCommand(): Promise<string> {
        return await invoke('app_handle_command', {  });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IEventGlobal  {
        return new EventGlobal();
    }
    //#endregion

}

// factory function
export function createEventGlobal(): T.IEventGlobal {
    return EventGlobal.create();
}
