// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.


import * as T from "../types/index"


export interface INestingTypeTest {

    /**
* * @brief Processes a given message.* * @param msg The message to process.* * @returns A string indicating the processed message.*/
    processMessage(msg: T.Data): Promise<string>;

}