
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : struct_test.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../interface/';

// tauri command interface class 
// target file : struct_test.rs
class StructTest implements T.IStructTest {

    //#region #tauri command
    
    /**
* ユーザー情報を取得するTauriコマンド**
     * # 引数* * `id` - ユーザーのID**
     * # 戻り値* 指定されたIDに対応するユーザー情報（ダミーデータ）*/
    async get_user_data(id: number): Promise<T.User> {
        return await invoke('get_user_data', { id: id });
    }
    
    /**
* 商品情報を取得するTauriコマンド**
     * # 引数* * `product_id` - 商品の識別子**
     * # 戻り値* 指定された商品IDに対応する商品情報（ダミーデータ）*/
    async get_product_data(product_id: string): Promise<T.Product> {
        return await invoke('get_product_data', { product_id: product_id });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IStructTest  {
        return new StructTest();
    }
    //#endregion

}

// factory function
export function createStructTest(): T.IStructTest {
    return StructTest.create();
}
