
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : event_test1.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../../interface/';

// tauri command interface class 
// target file : event_test1.rs
class EventTest1 implements T.IEventTest1 {

    //#region #tauri command
    
    /**
**/
    async eventTestCommand(): Promise<void> {
        return await invoke('event_test_command', {  });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IEventTest1  {
        return new EventTest1();
    }
    //#endregion

}

// factory function
export function createEventTest1(): T.IEventTest1 {
    return EventTest1.create();
}
