
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : event_window_many.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../../interface/';

// tauri command interface class 
// target file : event_window_many.rs
class EventWindowMany implements T.IEventWindowMany {

    //#region #tauri command
    
    /**
**/
    async emitMainEvent(payload: T.MainPayload): Promise<void> {
        return await invoke('emit_main_event', { payload: payload });
    }
    
    /**
**/
    async emitSubEvent(payload: T.SubPayload): Promise<void> {
        return await invoke('emit_sub_event', { payload: payload });
    }
    
    /**
**/
    async emitAnotherMainEvent(): Promise<void> {
        return await invoke('emit_another_main_event', {  });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IEventWindowMany  {
        return new EventWindowMany();
    }
    //#endregion

}

// factory function
export function createEventWindowMany(): T.IEventWindowMany {
    return EventWindowMany.create();
}
