
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : state.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../../interface/';

// tauri command interface class 
// target file : state.rs
class State implements T.IState {

    //#region #tauri command
    
    /**
**/
    async testState(): Promise<void> {
        return await invoke('test_state', {  });
    }
    
    /**
**/
    async testState2(name: string): Promise<void> {
        return await invoke('test_state2', { name: name });
    }
    
    /**
**/
    async testState3(name: string): Promise<void> {
        return await invoke('test_state3', { name: name });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IState  {
        return new State();
    }
    //#endregion

}

// factory function
export function createState(): T.IState {
    return State.create();
}
