
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : webview_window.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../../interface/';

// tauri command interface class 
// target file : webview_window.rs
class WebviewWindow implements T.IWebviewWindow {

    //#region #tauri command
    
    /**
**/
    async testWebviewWindow(): Promise<string> {
        return await invoke('test_webview_window', {  });
    }
    
    /**
**/
    async testWebviewWindow2(name: string): Promise<string> {
        return await invoke('test_webview_window2', { name: name });
    }
    
    /**
**/
    async testWebviewWindow3(name: string): Promise<string> {
        return await invoke('test_webview_window3', { name: name });
    }
    
    /**
**/
    async testWebviewWindow4(name: string): Promise<string> {
        return await invoke('test_webview_window4', { name: name });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IWebviewWindow  {
        return new WebviewWindow();
    }
    //#endregion

}

// factory function
export function createWebviewWindow(): T.IWebviewWindow {
    return WebviewWindow.create();
}
