// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.



export interface IWindow {

    /**
**/
    myCustomCommand(): Promise<void>;

}