// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.



export interface IWebviewWindow {

    /**
**/
    test_webview_window(): Promise<string>;

    /**
**/
    test_webview_window2(name: string): Promise<string>;

    /**
**/
    test_webview_window3(name: string): Promise<string>;

    /**
**/
    test_webview_window4(name: string): Promise<string>;

}