
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : event_test.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../../interface/';

// tauri command interface class 
// target file : event_test.rs
class EventTest implements T.IEventTest {

    //#region #tauri command
    
    /**
**/
    async eventTestCommand(): Promise<void> {
        return await invoke('event_test_command', {  });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IEventTest  {
        return new EventTest();
    }
    //#endregion

}

// factory function
export function createEventTest(): T.IEventTest {
    return EventTest.create();
}
