
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : window.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../interface/';

// tauri command interface class 
// target file : window.rs
class Window implements T.IWindow {

    //#region #tauri command
    
    /**
**/
    async myCustomCommand(): Promise<void> {
        return await invoke('my_custom_command', {  });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IWindow  {
        return new Window();
    }
    //#endregion

}

// factory function
export function createWindow(): T.IWindow {
    return Window.create();
}
