
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : response.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../../interface/';

// tauri command interface class 
// target file : response.rs
class Response implements T.IResponse {

    //#region #tauri command
    
    /**
**/
    async readFile1(): Promise<unknown> {
        return await invoke('read_file1', {  });
    }
    
    /**
**/
    async readFile2(): Promise<unknown> {
        return await invoke('read_file2', {  });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IResponse  {
        return new Response();
    }
    //#endregion

}

// factory function
export function createResponse(): T.IResponse {
    return Response.create();
}
