
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : app_handle.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../interface/';

// tauri command interface class 
// target file : app_handle.rs
class AppHandle implements T.IAppHandle {

    //#region #tauri command
    
    /**
**/
    async test_app_handle(): Promise<string> {
        return await invoke('test_app_handle', {  });
    }
    
    /**
**/
    async test_app_handle2(name: string): Promise<string> {
        return await invoke('test_app_handle2', { name: name });
    }
    
    /**
**/
    async test_app_handle3(name: string): Promise<string> {
        return await invoke('test_app_handle3', { name: name });
    }
    
    /**
**/
    async test_app_handle4(name: string): Promise<string> {
        return await invoke('test_app_handle4', { name: name });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IAppHandle  {
        return new AppHandle();
    }
    //#endregion

}

// factory function
export function createAppHandle(): T.IAppHandle {
    return AppHandle.create();
}
