
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : enum_test.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../interface/';

// tauri command interface class 
// target file : enum_test.rs
class EnumTest implements T.IEnumTest {

    //#region #tauri command
    
    /**
* * @brief Processes a given message.* * @param msg The message to process.* * @returns A string indicating the processed message.*/
    async processMessage(msg: T.Message): Promise<string> {
        return await invoke('process_message', { msg: msg });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.IEnumTest  {
        return new EnumTest();
    }
    //#endregion

}

// factory function
export function createEnumTest(): T.IEnumTest {
    return EnumTest.create();
}
