// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.


import * as T from "../types/index"


export interface ICmd1 {

    /**
* ユーザー情報を取得するTauriコマンド**
     * # 引数* * `id` - ユーザーのID**
     * # 戻り値* 指定されたIDに対応するユーザー情報（ダミーデータ）*/
    getUserData(id: number): Promise<T.User>;

}