// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.


import * as T from "../types/index"


export interface ICmd2 {

    /**
* 商品情報を取得するTauriコマンド**
     * # 引数* * `product_id` - 商品の識別子**
     * # 戻り値* 指定された商品IDに対応する商品情報（ダミーデータ）*/
    getProductData(product_id: string): Promise<T.Product>;

}