// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.



export interface IBasic {

    /**
* * @brief Greets the user.* * @param name The name of the user.* * @returns A greeting message.*/
    greet(name: string): Promise<string>;

    /**
* * @brief Adds two numbers.* * @param a The first number.* * @param b The second number.* * @returns The sum of the two numbers.*/
    add(a: number, b: number): Promise<number>;

    /**
* * @brief Gets a user by ID.* * @param id The ID of the user.* * @returns The user with the specified ID.*/
    getUser(id: number): Promise<string>;

    /**
* * @brief Updates a user.* * @param user_name The name of the user to update.* * @returns A message indicating the user has been updated.*/
    updateUser(user_name: string): Promise<string>;

}