// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.



export interface IAppHandle {

    /**
**/
    test_app_handle(): Promise<string>;

    /**
**/
    test_app_handle2(name: string): Promise<string>;

    /**
**/
    test_app_handle3(name: string): Promise<string>;

    /**
**/
    test_app_handle4(name: string): Promise<string>;

}