
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : cmd1.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../interface/';

// tauri command interface class 
// target file : cmd1.rs
class Cmd1 implements T.ICmd1 {

    //#region #tauri command
    
    /**
* ユーザー情報を取得するTauriコマンド**
     * # 引数* * `id` - ユーザーのID**
     * # 戻り値* 指定されたIDに対応するユーザー情報（ダミーデータ）*/
    async get_user_data(id: number): Promise<T.User> {
        return await invoke('get_user_data', { id: id });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.ICmd1  {
        return new Cmd1();
    }
    //#endregion

}

// factory function
export function createCmd1(): T.ICmd1 {
    return Cmd1.create();
}
