name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux (x86_64)
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: macOS (x86_64)
            os: macos-latest
            target: x86_64-apple-darwin
          - name: macOS (Apple Silicon)
            os: macos-latest
            target: aarch64-apple-darwin
          - name: Windows (x86_64)
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - name: Windows (ARM64)
            os: windows-latest
            target: aarch64-pc-windows-msvc

    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Get project version
        id: get_version
        run: echo "version=$(cargo pkgid | cut -d'#' -f2)" >> $GITHUB_OUTPUT

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.target }}-cargo-

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy --target ${{ matrix.target }} -- -D warnings

      - name: Run tests
        if: "!contains(matrix.target, 'aarch64')"
        run: cargo test --target ${{ matrix.target }} --verbose

      - name: Build
        run: cargo build --target ${{ matrix.target }} --verbose

      - name: Upload artifact (Unix)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: tauria-tsgen-v${{ steps.get_version.outputs.version }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/debug/tauria-tsgen

      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: tauria-tsgen-v${{ steps.get_version.outputs.version }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/debug/tauria-tsgen.exe