
// --- --- ---
// Note: This file was automatically generated by tauria-tsgen.
// Manually modifying it may break the interface and lead to unintended consequences. 
// Please exercise great caution if you choose to make manual changes.
//
// target file : cmd2.rs


import { invoke } from '@tauri-apps/api/core';
import * as T from '../interface/';

// tauri command interface class 
// target file : cmd2.rs
class Cmd2 implements T.ICmd2 {

    //#region #tauri command
    
    /**
* 商品情報を取得するTauriコマンド**
     * # 引数* * `product_id` - 商品の識別子**
     * # 戻り値* 指定された商品IDに対応する商品情報（ダミーデータ）*/
    async get_product_data(product_id: string): Promise<T.Product> {
        return await invoke('get_product_data', { product_id: product_id });
    }
    
    //#endregion


    //#region #endregion
    private constructor() {}

    static create(): T.ICmd2  {
        return new Cmd2();
    }
    //#endregion

}

// factory function
export function createCmd2(): T.ICmd2 {
    return Cmd2.create();
}
